# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shopping_demo
  username: shopping_demo_dba
  password: p2ssw0rd
  host: localhost
  port: 5432

test:
  <<: *default
  database: shopping_demo
  username: shopping_demo_dba
  password: p2ssw0rd
  host: localhost
  port: 5432

staging:
  <<: *default
  database: shopping_demo
  host: devdb01.cqbufnsbkdwl.us-east-1.rds.amazonaws.com
  username: shopping_demo_dba
  password: <%= ENV['SHOPPING-DEMO_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: shopping_demo
  host: devdb01.cqbufnsbkdwl.us-east-1.rds.amazonaws.com
  username: shopping_demo_dba
  password: <%= ENV['SHOPPING-DEMO_DATABASE_PASSWORD'] %>
